## Basic Configuration

baseurl = "https://csqsiew.netlify.app" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Cynthia Siew"
title = "Cynthia Siew"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
# enableRobotsTXT = true

## Site Settings
[params]
author = "Cynthia S. Q. Siew"
intro = "Psycholinguist who studies language networks."
description = "Assistant Professor at the National University of Singapore,<br/>but once a Jayhawk, always a Jayhawk."
authorimage = "profile2.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Cynthia S. Q. Siew"
keywords = ""

## Social Accounts
[params.social]
github = "csqsiew"
instagram = "csqsiew"
linkedin = "csqsiew"
twitter = "csqsiew"
email = "cynthia@nus.edu.sg"

## Extras
[params.extra]
copyright = "© 2021. CSQ Siew." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    weight = 50
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "research"
    weight = 100
    identifier = "research"
    url = "/research/"
[[menu.main]]
    name = "teaching"
    identifier = "teaching"
    weight = 200
    url = "/teaching/"
[[menu.main]]
    name = "Rcode"
    identifier = "Rcode"
    weight = 250
    url = "/Rcode/"
[[menu.main]]
    name = "studies"
    identifier = "studies"
    weight = 280
    url = "/studies/"
[[menu.main]]
    name = "scheduler"
    identifier = "appointments"
    weight = 300
    url = "/appointments/"
    